server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:litethinking_db}
    username: ${DB_USER:litethinking_user}
    password: ${DB_PASSWORD:litethinking_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvckxpdGVUaGlua2luZ1Byb2plY3QyMDI0ISFAQCMkJV4mKg==}
  expiration-ms: 86400000
